import React from "react";
import type { Filters, Row, UiState, OpsWorkItem } from "./model.js";
import { accessibleName } from "./model.js";
import { AUTHORITY_NOTICE } from "../constants.js";

export function OpsWorkView({state,rows,filters,onFilters,selectedId,onSelect,onRefresh,loading,now}:{state:UiState;rows:{active:Row[];attention:Row[];outcomes:Row[]};filters:Filters;onFilters:(f:Filters)=>void;selectedId:string|null;onSelect:(id:string|null)=>void;onRefresh:()=>void;loading:boolean;now:number}) {
 const selected=[...rows.active,...rows.attention,...rows.outcomes].find(r=>r.item.ops_task_id===selectedId)?.item;
 const projects=[...new Set([...rows.active,...rows.attention,...rows.outcomes].map(r=>r.item.project).filter((p):p is string=>!!p))].sort();
 const text=(v:unknown)=>v===null||v===undefined||v===""?"unknown":String(v);
 const update=(key:keyof Filters,value:string)=>onFilters({...filters,[key]:value});
 const itemName=(r:Row)=>accessibleName(r);
 const detail=(i:OpsWorkItem)=>Object.entries(i).filter(([k])=>k!=="source_links"&&k!=="usage"&&k!=="source_version");
 const section=(id:string,title:string,data:Row[],empty:string,heads:string[],cells:(r:Row)=>any)=> <section aria-labelledby={id} key={id}><h2 id={id}>{title} ({data.length})</h2>{data.length===0?<p>{empty}</p>:<table style={{borderCollapse:"collapse",width:"100%"}}><caption>{title}</caption><thead><tr>{heads.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{data.map((r,index)=><tr key={r.item.ops_task_id??index}>{cells(r)}</tr>)}</tbody></table>}</section>;
 return <main style={{fontFamily:"var(--font-mono, monospace)",padding:16}} aria-live="polite">
  <h1>Ops Work — observed</h1><p>{AUTHORITY_NOTICE}</p><button onClick={onRefresh} disabled={loading}>Refresh (read-only)</button>
  {state.kind==="loading"?<div role="status" aria-busy="true">Loading Ops work…<p aria-hidden="true">Loading snapshot…</p></div>:null}
  {state.kind==="error"?<div role="alert">Ops snapshot unavailable (fail closed)</div>:null}
  {state.kind==="malformed"?<div role="alert">Snapshot malformed or incompatible (fail closed): {state.reason}</div>:null}
  {state.kind==="ready"?<><p>Ops deployed SHA {text(state.envelope.snapshot.ops_deployed_sha).slice(0,12)} · fetched {state.fetchedAtIso}{state.envelope.cached?" · cached":""}</p>{state.stale?<div role="status">Stale data shown — source timestamp is older than 60 seconds.</div>:null}
   <fieldset><legend>Filters</legend><label htmlFor="ops-filter-query">Search</label><input id="ops-filter-query" type="search" placeholder="Search issue, task, repo" value={filters.query} onChange={e=>update("query",e.target.value)}/><label htmlFor="ops-filter-scope">Scope</label><select id="ops-filter-scope" value={filters.scope} onChange={e=>update("scope",e.target.value)}>{["all","active","attention","terminal"].map(x=><option key={x}>{x}</option>)}</select><label htmlFor="ops-filter-recency">Recency</label><select id="ops-filter-recency" value={filters.recency} onChange={e=>update("recency",e.target.value)}>{["any","24h","7d"].map(x=><option key={x}>{x}</option>)}</select><label htmlFor="ops-filter-project">Project</label><select id="ops-filter-project" value={filters.project} onChange={e=>update("project",e.target.value)}><option value="">All projects</option>{projects.map(p=><option key={p}>{p}</option>)}</select></fieldset>
   {section("active-work","Active work",rows.active,"No active work observed",["Project/Repo","Issue","Execution","Delegation","Last activity","Gate/Blocker"],r=><><td>{text(r.item.project)} / {text(r.item.repository)}</td><td>{text(r.item.issue_number)} {text(r.item.issue_title)}</td><td>{text(r.item.execution_state)}</td><td>{text(r.item.run_role)}{r.item.parent_run_id?` → ${r.item.parent_run_id}`:""}</td><td>{text(r.item.updated_at)}</td><td>{text(r.item.review_state)} / {text(r.item.blocker)}</td><td><button aria-label={`View details for ${itemName(r)}`} onClick={()=>onSelect(r.item.ops_task_id??null)}>View details</button></td></>)}
   {section("human-attention","Human attention",rows.attention,"No work waiting on human attention",["Item","Waiting reason","Updated","Source links"],r=><><td>{itemName(r)}</td><td>{r.attentionReason}</td><td>{text(r.item.updated_at)}</td><td>{Array.isArray(r.item.source_links)?r.item.source_links.map((href:any)=><a key={String(href)} href={String(href)} target="_blank" rel="noreferrer">{String(href)}</a>):"unknown"}</td><td><button aria-label={`View details for ${itemName(r)}`} onClick={()=>onSelect(r.item.ops_task_id??null)}>View details</button></td></>)}
   {section("recent-outcomes","Recent outcomes",rows.outcomes,"No recent outcomes observed",["Item","Outcome","Updated","PR"],r=><><td>{itemName(r)}</td><td>{r.outcomeLabel} <span>{r.outcomeKind}</span></td><td>{text(r.item.updated_at)}</td><td>{r.item.pr_number==null?"unknown":`#${r.item.pr_number}`}</td><td><button aria-label={`View details for ${itemName(r)}`} onClick={()=>onSelect(r.item.ops_task_id??null)}>View details</button></td></>)}
   {selected?<aside><h2>Work item details</h2><button onClick={()=>onSelect(null)}>Close</button><dl>{detail(selected).map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{text(v)}</dd></React.Fragment>)}{Object.entries(selected.usage??{}).map(([k,v])=><React.Fragment key={k}><dt>usage · {k}</dt><dd>{text(v)}</dd></React.Fragment>)}{Object.entries(selected.source_version??{}).map(([k,v])=><React.Fragment key={k}><dt>source_version · {k}</dt><dd>{text(v)}</dd></React.Fragment>)}</dl>{(Array.isArray(selected.source_links)?selected.source_links:[]).map((href:any)=><a key={String(href)} href={String(href)} target="_blank" rel="noreferrer">{String(href)}</a>)}</aside>:null}
  </>:null}</main>;
}
