import React from "react";
import type { Filters, Row, UiState, OpsWorkItem } from "./model.js";
import { accessibleName, summarize, formatRecency, blockSummary } from "./model.js";
import { AUTHORITY_NOTICE } from "../constants.js";

export function OpsWorkView({state,rows,filters,onFilters,selectedId,onSelect,onRefresh,loading,now,items,refreshFailed}:{state:UiState;rows:{active:Row[];attention:Row[];outcomes:Row[]};filters:Filters;onFilters:(f:Filters)=>void;selectedId:string|null;onSelect:(id:string|null)=>void;onRefresh:()=>void;loading:boolean;now:number;items:OpsWorkItem[];refreshFailed:boolean}) {
 const selected=[...rows.active,...rows.attention,...rows.outcomes].find(r=>r.item.ops_task_id===selectedId)?.item;
 const detailRef=React.useRef<HTMLElement>(null);
 const invokingButtonRef=React.useRef<HTMLButtonElement|null>(null);
 React.useEffect(()=>{if(selectedId!==null&&selected){detailRef.current?.focus();detailRef.current?.scrollIntoView({block:"nearest"});}},[selectedId]);
 const closeDetails=()=>{onSelect(null);if(invokingButtonRef.current?.isConnected)invokingButtonRef.current.focus();};
 const projects=[...new Set(items.map(i=>i.project).filter((p):p is string=>!!p))].sort();
 const text=(v:unknown)=>v===null||v===undefined||v===""?"unknown":String(v);
 const update=(key:keyof Filters,value:string)=>onFilters({...filters,[key]:value});
 const itemName=(r:Row)=>summarize(accessibleName(r),60);
 const detailsButton=(r:Row)=><button type="button" aria-label={`View details for ${accessibleName(r)}`} aria-current={selectedId===r.item.ops_task_id?"true":undefined} onClick={e=>{invokingButtonRef.current=e.currentTarget;if(selectedId===r.item.ops_task_id){detailRef.current?.focus();detailRef.current?.scrollIntoView({block:"nearest"});}onSelect(r.item.ops_task_id??null);}}>View details{selectedId===r.item.ops_task_id?" (selected)":""}</button>;
 const detail=(i:OpsWorkItem)=>Object.entries(i).filter(([k])=>k!=="source_links"&&k!=="usage"&&k!=="source_version");
 const section=(id:string,title:string,data:Row[],empty:string,heads:string[],cells:(r:Row)=>any)=> <section aria-labelledby={id} key={id}><h2 id={id}>{title} ({data.length})</h2>{data.length===0?<p>{empty}</p>:<table style={{borderCollapse:"collapse",width:"100%"}}><caption>{title}</caption><thead><tr>{heads.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{data.map((r,index)=><tr key={r.item.ops_task_id??index}>{cells(r)}</tr>)}</tbody></table>}</section>;
 return <main style={{fontFamily:"var(--font-mono, monospace)",padding:16}}><div role="status" aria-live="polite">{refreshFailed?"Refresh failed; showing last observed snapshot":state.kind==="loading"?"Loading Ops work":state.kind==="error"?"Ops snapshot unavailable":state.kind==="malformed"?"Snapshot malformed":state.stale?"Stale data shown":"OK"}</div>
  <h1>Ops Work — observed</h1><p>{AUTHORITY_NOTICE}</p><button onClick={onRefresh} disabled={loading}>Refresh (read-only)</button>
  {state.kind==="loading"?<div role="status" aria-busy="true">Loading Ops work…<p aria-hidden="true">Loading snapshot…</p></div>:null}
  {state.kind==="error"?<div role="alert">Ops snapshot unavailable (fail closed)</div>:null}
  {state.kind==="malformed"?<div role="alert">Snapshot malformed or incompatible (fail closed): {state.reason}</div>:null}
  {state.kind==="ready"?<>{refreshFailed?<div role="status">Refresh failed — showing last observed snapshot (fail closed)</div>:null}{state.malformedItemCount>0?<div role="status">{state.malformedItemCount} malformed item{state.malformedItemCount===1?"":"s"} skipped (fail closed)</div>:null}<p>Ops deployed SHA {text(state.envelope.snapshot.ops_deployed_sha).slice(0,12)} · fetched {state.fetchedAtIso}{state.envelope.cached?" · cached":""}</p>{state.stale?<div role="status">Stale data shown — source timestamp is older than 60 seconds.</div>:null}
   <fieldset><legend>Filters</legend><label htmlFor="ops-filter-query">Search</label><input id="ops-filter-query" type="search" placeholder="Search issue, task, repo" value={filters.query} onChange={e=>update("query",e.target.value)}/><label htmlFor="ops-filter-scope">Scope</label><select id="ops-filter-scope" value={filters.scope} onChange={e=>update("scope",e.target.value)}>{["all","active","attention","terminal"].map(x=><option key={x}>{x}</option>)}</select><label htmlFor="ops-filter-recency">Recency</label><select id="ops-filter-recency" value={filters.recency} onChange={e=>update("recency",e.target.value)}>{["any","24h","7d"].map(x=><option key={x}>{x}</option>)}</select><label htmlFor="ops-filter-project">Project</label><select id="ops-filter-project" value={filters.project} onChange={e=>update("project",e.target.value)}><option value="">All projects</option>{projects.map(p=><option key={p}>{p}</option>)}</select></fieldset>
   {section("human-attention","Human attention",rows.attention,"No work waiting on human attention",["Item","Waiting reason","Recency","Gate/blocker summary","Details"],r=><><td>{itemName(r)}</td><td>{summarize(r.attentionReasons?.join(", ")??text(r.attentionReason),60)}</td><td>{formatRecency(r.item.updated_at,now)}</td><td>{blockSummary(r.item)}</td><td>{detailsButton(r)}</td></>)}
   {section("active-work","Active work",rows.active,"No active work observed",["Item","Execution state","Delegation","Recency","Gate/blocker summary","Details"],r=><><td>{itemName(r)}</td><td>{summarize(text(r.item.execution_state),40)}</td><td>{summarize(text(r.item.run_role),40)}</td><td>{formatRecency(r.item.updated_at,now)}</td><td>{blockSummary(r.item)}</td><td>{detailsButton(r)}</td></>)}
   {section("recent-outcomes","Recent outcomes",rows.outcomes,"No recent outcomes observed",["Item","Outcome","Recency","PR number","Details"],r=><><td>{itemName(r)}</td><td>{summarize(text(r.outcomeLabel),40)} <span>{summarize(text(r.outcomeKind),20)}</span></td><td>{formatRecency(r.item.updated_at,now)}</td><td>{r.item.pr_number==null?"unknown":summarize(`#${r.item.pr_number}`,20)}</td><td>{detailsButton(r)}</td></>)}
   {selected?<aside role="region" aria-labelledby="ops-detail-heading" tabIndex={-1} ref={detailRef} onKeyDown={e=>{if(e.key==="Escape"){e.stopPropagation();closeDetails();}}}><h2 id="ops-detail-heading">Work item details</h2><button type="button" onClick={closeDetails}>Close</button><dl>{detail(selected).map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{text(v)}</dd></React.Fragment>)}{Object.entries(selected.usage??{}).map(([k,v])=><React.Fragment key={k}><dt>usage · {k}</dt><dd>{text(v)}</dd></React.Fragment>)}{Object.entries(selected.source_version??{}).map(([k,v])=><React.Fragment key={k}><dt>source_version · {k}</dt><dd>{text(v)}</dd></React.Fragment>)}<dt>source_links</dt><dd>{Array.isArray(selected.source_links)&&selected.source_links.length>0?selected.source_links.map((href:any,index:number)=><a key={`${href}#${index}`} style={{display:"inline-block",marginRight:8}} href={String(href)} target="_blank" rel="noreferrer">{String(href)}</a>):"unknown"}</dd></dl></aside>:null}
  </>:null}</main>;
}
